ARG BASE_VER=2.26.3

FROM yocents/git:${BASE_VER}

RUN set -ex && \
    apk add --no-cache git-daemon

VOLUME ["/data"]

COPY entrypoint.daemon.sh /entrypoint.sh

ENV HOME=/data

ENTRYPOINT ["/entrypoint.sh"]

EXPOSE 9418

CMD ["/usr/bin/git", "daemon", "--export-all", "--reuseaddr", "--base-path=/data", "/data"]
