ARG BASE_VER=3.1.3

FROM yocents/rsync:${BASE_VER}

RUN set -ex && \
    apk add --no-cache openssh-server

EXPOSE 22

COPY entrypoint.ssh.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

CMD ["/usr/sbin/sshd", "-D", "-e"]
