ARG OS_VER=3.12

FROM alpine:${OS_VER}

RUN set -ex && \
    sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories && \
    apk add --no-cache --no-scripts apache2-utils

ENTRYPOINT ["/usr/bin/htpasswd"]

CMD ["-h"]
